from core.exceptions.app import AppError


class DbError(AppError):
    pass
